name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Lint
      run: yarn lint
    
    - name: Build
      run: yarn build
      env:
        NEXT_PUBLIC_API_URL: http://localhost:3000

  security:
    runs-on: ubuntu-latest
    # Make this job optional
    continue-on-error: true
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check for Snyk token
      id: check_token
      run: |
        if [ "${{ secrets.SNYK_TOKEN }}" != "" ]; then
          echo "has_token=true" >> $GITHUB_OUTPUT
        else
          echo "has_token=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Run Snyk to check for vulnerabilities
      if: steps.check_token.outputs.has_token == 'true'
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high
