name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Build
      run: npm run build
      env:
        NEXT_PUBLIC_API_URL: http://localhost:3000

  security:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Snyk CLI
      run: npm install -g snyk
    
    - name: Authenticate with Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true
    
    - name: Run Snyk security scan
      run: |
        if command -v snyk &> /dev/null && snyk test --json > /dev/null 2>&1; then
          snyk test --severity-threshold=high
        else
          echo "Skipping Snyk scan - not configured"
          exit 0
        fi
      continue-on-error: true
